---
title: "perim-analysis"
author: "Alex Jack"
date: "2023-07-31"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, load packages}
#library("rgdal")
library("raster")
library("sf")
library("leafsync")
library(stars)
library("ggplot2")
library("stars")
library(XML)
library(spatialEco)
library(spatstat.random)
library(landscapemetrics)
library(maps)
library(reshape2)
library(exifr)
library(gtools)
library(dplyr)
library(jsonlite)
library(stringr)
library(scales)
library(ggrepel)
library(landscapemetrics)
library(ggrepel)
library(tidyverse)
library(RColorBrewer)
library(car)
library(MASS)
library(lme4)
library(DHARMa)
library(finalfit)
library(car)
library(effects)
library(gt)
library(DataEditR)
library(pscl)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(webshot)
```

```{r, load data create global constants}
# TODO anonymize the farmers, i.e. rename all shps and to correlate with SIDs,
# restructure file structure

utm <- st_crs("+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs")

# create three buffer distances
buffDistSml <- 1000 # 1km
buffDistMed <- 3000 # 3km
buffDistLrg <- 5000 # 5km
rastpathMNWI <- "C:/Users/jackx/Desktop/landcover-tif/clipped-area/clipped-area.tif"

camDat<-read.table(
  "./data/cam-dat.csv",
  sep=",", header=TRUE, quote="")

imgDatf<-read.table(
  "./data/imgDatf.csv",
  sep=",", header=TRUE)
imgDatw<-read.table(
  "./data/imgDatw.csv",
  sep=",", header=TRUE)
imgDats<-read.table(
  "./data/imgDats.csv",
  sep=",", header=TRUE)
siteCovariates <-read.table(
  "./data/site-covariates.csv",
  sep=",", header=TRUE)
#imgDat <- imgDatw
imgDatf <- imgDatf[,-c((ncol(imgDatf)-1))]
imgDat <- data.frame()
imgDat <- rbind(imgDatf,imgDats,imgDatw)

lcDat<-read.table(
  "./data/camDatSummary")
roadDensDat<-read.table("./data/roadDensDat")
roadDensDat$sid<-toupper(roadDensDat$sid)

lsmDat <- read.table("./data/lsmDat")
sites<-read.table("./data/siteS05split") # df to hold all timestamps of all images

# final version of imgDat
# includes inSample Period; contains all sites
# duplicated values
imgDat <- read.table("./data/imgDatFinal")

# read in raster
landcoverMNWI<-raster(rastpathMNWI)
landcoverPA <- raster("./perim-shapefiles/nlcd-landcover-PA/nlcd-landcover-PA.tif")

#  read in shp file
farm.full<-st_read(S01)
S01 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\ken-williams\\Shapefiles\\ken-williams.shp")
# READ in SHP files for each farm
S01 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\ken-williams\\Shapefiles\\ken-williams.shp")
S02 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\mark-volk\\Shapefiles\\mark-volk.shp")
S03 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\deb-holthaus\\Shapefiles\\deb-holthaus.shp")
S04<-st_read("C:\\Users\\jackx\\Desktop\\perim-data\\Cervid-Farm\\AntlerAdventureBuffer.shp")
S05b<-st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\scott-fier\\Shapefiles\\scott-fier-1.shp") # will need to load up each
S05a<-st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\scott-fier\\Shapefiles\\scott-fier-main-2.shp")
S05c<-st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\scott-fier\\Shapefiles\\scott-fier-ext-natural.shp")
S05d<-st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\scott-fier\\Shapefiles\\scott-fier-ext-small.shp")
S06<-st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\gary-olson\\Shapefiles\\gary-olson.shp")
S09 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\chad-jelinek\\Shapefiles\\chad-jelinek.shp")
S11 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\steve-uchytil\\Shapefiles\\steve-uchytil.shp")
S12 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\troy-anderson\\Shapefiles\\troy-anderson.shp")

# PA farms
S07<-st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\gerald-reed\\gerald-reed.shp")
S10 <- st_read("C:\\Users\\jackx\\Desktop\\perim-analysis\\perim-shapefiles\\glenn-dice\\glenn-dice.shp")
```
```{r, create dataframe of areas}
farms <- c("S01","S02", "S03", "S04", "S05a", "S05b", "S05c", "S05d", "S06", "S07", "S09", "S10", "S11", "S12")
huntranch <- c("S07", "S04")
breedop <- c("S01","S02", "S03", "S05a", "S05b", "S05c", "S05d", "S06", "S09", "S10", "S11", "S12")
farmSizedf <- data.frame(farm_id = farms, sizekm2=0, sizemi2=0)
for(j in 1:nrow(farmSizedf)){
  farm<-get(farmSizedf[j,]$farm_id)
  if(farms[j] == "S01" || farms[j] == "S04"){ 
    farmSizedf[j,]$sizekm2 <- st_area(nngeo::st_remove_holes(farm))/1000000
    farmSizedf[j,]$sizemi2 <- farmSizedf[j,]$sizekm2 * 0.386102
  }else{
    farmSizedf[j,]$sizekm2 <- st_area(farm)/1000000
    farmSizedf[j,]$sizemi2 <- farmSizedf[j,]$sizekm2 * 0.386102
  }
}
# mean and sd of breed op
print("Size Breed Op: ")
print(paste0("mean size km: ", mean(farmSizedf[which(farmSizedf$farm_id %in% breedop),]$sizekm2)))
print(paste0("mean size mi: ", mean(farmSizedf[which(farmSizedf$farm_id %in% breedop),]$sizemi2)))
print(paste0("sd km: ",sd(farmSizedf[which(farmSizedf$farm_id %in% breedop),]$sizekm2)))
print(paste0("sd mi: ", sd(farmSizedf[which(farmSizedf$farm_id %in% breedop),]$sizemi2)))
# mean and sd of hr

print("Size Hunt Ranch: ")
print(paste0("mean size km: ",mean(farmSizedf[which(farmSizedf$farm_id %in% huntranch),]$sizekm2)))
print(paste0("mean size mi: ",mean(farmSizedf[which(farmSizedf$farm_id %in% huntranch),]$sizemi2)))
print(paste0("sd km: ", sd(farmSizedf[which(farmSizedf$farm_id %in% huntranch),]$sizekm2)))
print(paste0("sd mi: ", sd(farmSizedf[which(farmSizedf$farm_id %in% huntranch),]$sizemi2)))
```

```{r helper functions}
splitJPGS <- function(dataframe, uidName){
  for(i in 1:nrow(dataframe)){
  # strip away the .JPG suffix; if there is one
  if(grepl(".JPG", dataframe[i,uidName])){
    dataframe[i,uidName] <- strsplit(dataframe[i,uidName], "\\.")[[1]][1]
  }
  
  }
  return(dataframe)
}
# subset time to two weeks
subsetTime<-function(deployDat, samplePeriod=14, deployDateCol, imgDateCol){
  for(i in 1:nrow(deployDat)){
    deployDateColNum<-which(colnames(deployDat)==deployDateCol)
    imgDateColNum<-which(colnames(deployDat)==imgDateCol)
    # to account for differences in date format
    if(!is.na(deployDat[i,imgDateColNum])  & !is.na(deployDat[i,deployDateColNum])){
    if(!is.na(strptime(deployDat[i,imgDateColNum], "%Y-%m-%d"))){
      imgDate <- strptime(deployDat[i,imgDateColNum], "%Y-%m-%d")
    }
    else{
      imgDate <- strptime(deployDat[i,imgDateColNum], "%Y:%m:%d")
    }
    if(abs(difftime(strptime(deployDat[i,deployDateColNum], "%Y-%m-%d", tz = ""), imgDate, units='days', tz = "")) <= 14){
      deployDat[i,]$inSamplePeriod <- TRUE
      }
    }else{
      deployDat[i,]$inSamplePeriod <- NA
    }
  }
return(deployDat)desi
}
subsetTimeHard<-function(deployDat, samplePeriod=14, deployDate, imgDateCol){
  for(i in 1:nrow(deployDat)){
    #deployDateColNum<-which(colnames(deployDat)==deployDateCol)
    imgDateColNum<-which(colnames(deployDat)==imgDateCol)
    # to account for differences in date format
    if(!is.na(deployDate)  & !is.na(deployDate)){
    if(!is.na(strptime(deployDat[i,imgDateColNum], "%Y-%m-%d"))){
      imgDate <- strptime(deployDat[i,imgDateColNum], "%Y-%m-%d")
    }
    else{
      imgDate <- strptime(deployDat[i,imgDateColNum], "%Y:%m:%d")
    }
    if(abs(difftime(strptime(deployDate, "%Y-%m-%d", tz = ""), imgDate, units='days', tz = "")) <= 14){
      deployDat[i,]$inSamplePeriod <- TRUE
      }
    }else{
      deployDat[i,]$inSamplePeriod <- NA
    }
  }
return(deployDat)
}

```


```{r create sites dataframe to hold temporal data}

# use this to sort images into field scans and triggers

base <- "C:/Users/jackx/Desktop/dataTables"
files <- list.files(base, recursive = FALSE, full.names = FALSE)
imgs <- c()
dirs <- list.dirs(base, recursive = FALSE, full.names = FALSE) # get all of the ca
#for(i in 1:length(dirs)){
#posImgs <- list.files(path=paste0(base,"/", dirs[i], "/", "positive-images"), full.names = TRUE, pattern = ".JPG")
#   emptyImgs <- list.files(path=paste0(base,"/", dirs[i], "/", "empty"), full.names=TRUE, pattern=".JPG")
#   imgs<-c(imgs,posImgs, emptyImgs)
# }
# create a dataframe to hold information about the images
SO1<-S01
# i = 2, 3, 5, 6, 9

names(sites) <- strsplit(names(sites),".")
sites <- sites %>% as.data.frame()
sites <- read.table(paste0(base, "/", files[1]), fill=TRUE)
for(i in 2:length(files)){
      site<-read.table(paste0(base, "/", files[i]), fill=TRUE)
      sites <-rbind(sites, site)
}
s05 <- sites %>% filter(site=="S05")
sites <- sites %>% filter(site!="S05")
for(i in 1:nrow(s05)){
if((s05[i,]$cam %in% c("A49","A08","A105","A59","A58","A10"))){
    s05[i,]$site <- 'S05a'
  }
  if((s05[i,]$cam %in% c("A42","A86","A91","A106","A29","A104"))){
        s05[i,]$site <- 'S05b'
  }
    if((s05[i,]$cam %in% c("A07","A32","A36","A107","A108","A13","A95","A131","A111",                  "A67","A38","A99","A05","A40","A22","A94"))){
      s05[i,]$site <- 'S05c'
    }
      if((s05[i,]$cam %in% c("A26","A103","A132","A85","A06","A110"))){
        s05[i,]$site <- 'S05d'
      }
}
sites <- rbind(sites, s05)
# 
# sites<-read.table("./data/siteS05split")
# sites<-sites %>% filter(site != "")
imgDat<-splitJPGS(imgDat, "imgID")
sites$deployString <- paste0(sites$season, "-", sites$site, "-", sites$cam)
sites$deployString <- toupper(sites$deployString)
write.table(sites.m, "./data/siteS05splitComplete")
sites <- read.table("./data/siteS05splitComplete") # complete has the inSamplePeriod Parm
```

```{r, read in all image tables}

tables <- list.files(imgTablesTimeStampPath, recursive = FALSE, full.names = TRUE)
timeStampDat <- data.frame()
s01TimeStamp <- read.table(tables[1])
s02TimeStamp <- read.table(tables[2])
s03TimeStamp <- read.table(tables[3])
s05TimeStamp <- read.table(tables[4])
s07TimeStamp <- read.table(tables[5])
s11TimeStamp <- read.table(tables[6])
s12TimeStamp <- read.table(tables[7])
```
```{r summarize camera data}
camDatSummary<- camDat %>% group_by(sid) %>% filter(season=='S') %>% filter(feeder == FALSE) %>% filter(is.na(improperFormat)) %>% summarise(sumimgs = sum(numImages), n = n())
``` 
```{r summarise by cid and sid}
camDatSummaryc <- camDat %>% filter(season=='S') %>% filter(!is.na(numImages)) %>% filter(feeder == FALSE) %>% filter(is.na(improperFormat)) 
camDatSummaryC <- camDatSummaryc %>% group_by(sid, cid)
```
```{r, get farm buffers}
propForestDat<-camDatSummary
propForestDat$propForest1k <- 0
propForestDat$propForest3k <- 0
propForestDat$propForest5k <- 0
# grab the extent of our farm
farms <- c("S01","S02", "S03", "S04", "S05a", "S05b", "S05c", "S05d", "S06", "S07", "S09", "S10", "S11", "S12")
for(j in 1:length(farms)){
  if(farms[j] == "S07" || farms[j] == "S10"){
    landcover <- landcoverPA
  }
  else{
    landcover <- landcoverMNWI
  }
  #  farm<-st_transform(get(farms[i]), crs(landcover))

  farm<-st_transform(get(farms[j]), crs(landcover))
  farm.extent<-extent(farm)
  farm.extent<-extend(farm.extent, buffDistLrg*2)
  #landcoverMNWI<-projectExtent(landcoverMNWI, crs(s01))
  # crop our lc dataset to the buffered extent
  lc.cropped<-crop(landcover, farm.extent) %>% 
  st_as_stars() %>%
  st_as_sf()
farmBuffSml<-farm %>%
  st_buffer(buffDistSml) # buffer by 30m

farmBuffMed<-farm %>%
  st_buffer(buffDistMed) # buffer by 30m

farmBuffLrg<-farm %>%
  st_buffer(buffDistLrg) # buffer by 30m

# subtract the buffered farm from the original shp
# farm.fenceline.buff<-st_difference(farmBuffSml, farm.full)

# intersect our fencline and our cropped landcover tif
lcFullSml<-st_intersection(lc.cropped, farmBuffSml)
lcFullMed<-st_intersection(lc.cropped, farmBuffMed)
lcFullLrg<-st_intersection(lc.cropped, farmBuffLrg)
# lcFullSml <- st_intersection(lc.cropped, lcFenclineSml)
# lcFullMed <- st_intersection(lc.cropped, lcFenclineMed)
# lcFullLrg <- st_intersection(lc.cropped, lcFenclineLrg)
# convert back to raster so we can use sampleStratified
lcFullSmlRast<-st_rasterize(lcFullSml)
lcFullMedRast<-st_rasterize(lcFullMed)
lcFullLrgRast<-st_rasterize(lcFullLrg)

if(farms[j] == "S07" || farms[j] == "S10"){
lAIFarmDat[which(lAIFarmDat$sid==farms[j]),]$ai1k<-lsm_l_ai(lcFullSmlRast$nlcd.landcover.PA)$value
lAIFarmDat[which(lAIFarmDat$sid==farms[j]),]$ai3k<-lsm_l_ai(lcFullMedRast$nlcd.landcover.PA)$value
lAIFarmDat[which(lAIFarmDat$sid==farms[j]),]$ai5k<-lsm_l_ai(lcFullLrgRast $nlcd.landcover.PA)$value
}else{
lAIFarmDat[which(lAIFarmDat$sid==farms[j]),]$ai1k<-lsm_l_ai(lcFullSmlRast$clipped.area)$value
lAIFarmDat[which(lAIFarmDat$sid==farms[j]),]$ai3k<-lsm_l_ai(lcFullMedRast$clipped.area)$value
lAIFarmDat[which(lAIFarmDat$sid==farms[j]),]$ai5k<-lsm_l_ai(lcFullLrgRast$clipped.area)$value  
}

}


```
```{r}
imgDat$season <- ""
imgDat$site <- ""
imgDat$cam <- ""
imgDat$imgNum <- 0
imgDat$num <- 0

# remove unwanted speces

imgDat <- imgDat %>% mutate(class=if_else(spcs=="possum", "furbearer", class))
imgDat <- imgDat %>% mutate(class=if_else(spcs=="striped skunk", "furbearer", class))
imgDat <- imgDat %>% filter(!(spcs %in% c("cottontail", " grey squirrel",  "grey squirrel"))) %>% mutate(spcs = str_replace_all(spcs, c("great horned owl" = "great-horned owl", "raccooon" = "raccoon", "hawk"="unknown hawk sp.", "grey-squirrel"="squirrel", "grey squirrrel" = "squirrel","striped skunk" = "skunk", "grey squirrel" = "squirrel", "groundhog; cottontail" = "groundhog", "fox squirrrel"="squirrel", "fox squirrel"="squirrel", "13 lined groundsquirrel" = "squirrel", "sp. unknown" = "sp unknown","sp unkown"="sp unknown"))) %>% filter(!(spcs%in% c("squirrel", "cottontail", "great-horned owl", "unkown hawk sp.", "chipmunk", "groundhog", "cow"))) %>% filter(!(class== "deer" & loc== "I")) %>% filter(class!="bird") %>%  filter(class!="small-mam")
imgDat <- imgDat %>% mutate(spcs = str_replace_all(spcs, c("bobcat" = "bob"))) %>% filter(spcs != "domestic cat") %>% filter(spcs != "cat") %>% filter(spcs != "dog") %>% filter(spcs != "domestic dog") 

# standardize naming conventions
imgDat <- imgDat %>% mutate(class = str_replace_all(class, c("meso-carn" = "furbearer", "carnivore" = "furbearer"))) %>% mutate(spcs = if_else(class=="deer","white-tailed deer",spcs)) %>% mutate(class = if_else(class=="Vague ID ", "Vague ID", class))

imgDat <- imgDat %>% mutate(spcs = if_else(spcs=="bob", "bobcat", spcs))
# standardize case
imgDat$spcs <- tolower(imgDat$spcs)

# standardize vague ID class 
imgDat[c(which(imgDat$spcs=="" & imgDat$class!="")),]$spcs <- "sp unknown"
imgDat <- imgDat %>% filter(spcs != "")
# strip site, camera and season from unique imgID
for(i in 1:nrow(imgDat)){
  if(grepl(".JPG",imgDat[i,]$imgID)){
      imgID<-strsplit(imgDat[i,]$imgID, "\\.")[[1]][1]
      uidStringArr <- strsplit(imgID, "-")[[1]]
  }
  if(!grepl(".JPG",imgDat[i,]$imgID)){
      uidStringArr <- strsplit(imgDat[i,]$imgID, "-")[[1]]
  }
  imgDat[i,]$season <- toupper(uidStringArr[1])
  imgDat[i,]$site <- toupper(uidStringArr[2])
  imgDat[i,]$cam <- uidStringArr[3]
  imgDat[i,]$imgNum <- as.integer(uidStringArr[4])
}

S05 <- imgDat %>% filter(site == "S05")
imgDat <- imgDat %>% filter(site != "S05")
# split S05 by facility
for(i in 1:nrow(S05)){
  if(S05[i,]$cam %in% c("A49","A08","A105","A59","A58","A10")){
    S05[i,]$site <- 'S05A'
}
  if(S05[i,]$cam %in% c("A42","A86","A91","A106","A29","A104")){
        S05[i,]$site <- 'S05B'
  }
    if((S05[i,]$cam %in% c("A07","A32","A36","A107","A108","A13","A95","A131","A111",                  "A67","A38","A99","A05","A40","A22","A94"))){
      S05[i,]$site <- 'S05C'
    }
      if(S05[i,]$cam %in% c("A26","A103","A132","A85","A06","A110")){
        S05[i,]$site <- 'S05D'
      }
}
imgDat<-rbind(imgDat, S05)
imgDat$site <- toupper(imgDat$site)
# create unique deploy string
imgDat$deployString = paste0(imgDat$season, "-", imgDat$site, "-", imgDat$cam)
imgDat <- imgDat[-c(which(imgDat$site=='S05C' & imgDat$cam == "A95")),] # remove feeder
imgDatUSeq <- imgDat %>% filter(sequenceID != 0)
imgDatUSeqplotor <-  imgDatUSeq %>% mutate(spcs = str_replace_all(spcs, c("striped skunk" = "skunk")))
imgDatUSeqplotor <- imgDatUSeqplotor %>% filter(spcs %in% c("raccoon","skunk","possum"))

# replace blank species name and + class ID with sp unknown
imgDat <- imgDat %>% filter(!(class=="" & spcs==""))
```
```{r}
sites$deployString <- paste0(sites$season, "-", sites$site, "-", sites$cam)
imgDat$deployString <- toupper(imgDat$deployString)
camDat$deployString <- paste0(toupper(camDat$season),"-",toupper(camDat$sid), "-",toupper(camDat$cid))

imgDatm <- merge(imgDatm, camDat, all.X=TRUE, on.x=c('deployString'), on.y=c('deployString'))


imgDat <- splitJPGS(imgDat, "imgID")
imgDat$imgID <- toupper(imgDat$imgID)
feeders <- imgDatm %>% filter(feeder==TRUE)
feeders <- camDat[which(camDat$feeder==TRUE),]
feeders$deployString <- paste0(feeders$season,"-", feeders$sid, "-",feeders$cid)
feederDeploys <- unique(feeders$deployString)
imgDatm <- imgDatm %>% filter(feeder==FALSE)
imgDat$uSeq <- paste0(imgDat$deployString,"-", imgDat$sequenceID)
imgDat <- imgDat %>% filter(sequenceID !=0)
write.table(imgDatm, './data/imgDatClean')
write.table(feeders,'./data/feeders') # list of feeders
read.table("./data/feeders")
# merge with sites
sites.m$season<-toupper(sites.m$season)
sites.m$site<-toupper(sites.m$site)
sites.m$cam<-toupper(sites.m$cam)
sites.m$imgID <- paste0(sites.m$season, "-", sites.m$site, "-", sites.m$cam, "-", sites.m$imgNum)
imgDat2 <- imgDat %>% filter(!is.na(numInds))
# first I need to change the "date" column to a string
sites.m <- sites.m %>% mutate(date.chr = as.character(date))
imgDat$imgID <- toupper(imgDat$imgID)
imgDatm <- merge(sites.m, imgDat, on.x="imgID", on.y="imgID", all.y=TRUE)
```

```{r, summarise by class and species}
imgDatUSeq <- splitJPGS(imgDatUSeq, "imsgID") # split off any 
imgDatUSeq$useq <- paste0(imgDatUSeq$deployString, "-", imgDatUSeq$sequenceID)
imgDatUSeqplotor$useq <- paste0(imgDatUSeqplotor$deployString, "-", imgDatUSeqplotor$sequenceID)
imgDatUSeq <- imgDatm %>% filter(!duplicated(useq))
imgDatUSeq <- imgDatUSeq %>% filter(!duplicated(imgDatUSeq$useq))

imgDatUSeqDup <- imgDatUSeq[-c(duplicated(imgDatUSeq)),] # get rid of duplicate row

imgDatUSeqPivotSummer <- imgDatUSeq %>% group_by(site, spcs) %>% filter(season=="S") %>% summarise(n=n()) %>% pivot_wider(id_cols = site, values_from = n, names_from=spcs, values_fill=0)



# this generates a table for the sightings by species on each site
imgDatUSeqSummary <- imgDatUSeq %>% group_by(class) %>% summarise(n=n())
imgDatUSeqSummarySpcsBySite <- imgDatUSeq  %>% group_by(spcs) %>% summarise(n = n(), prop=n()/nrow(imgDatUSeq))

#write.table(imgDatUSeqPivotSummer, "./data/speciesSummaryBySite", sep=",")

# remove the splotch that we thought might be a bear
imgDatUSeq <- imgDatUSeq[-c(which(imgDatUSeq$uid=="s-S10-A68-3317")),]

imgDatUSeqSpcsT<-imgDatUSeq %>% group_by(spcs) %>% summarise(n=n()) %>% mutate(percent=n/nrow(imgDatUSeq))
write.table(imgDatUSeqSpcsT, "./data/imgDatUSeqSpcsT", sep=",") # for total species for all seaons

print(paste0("Total independent observations where deer were present ", imgDatUSeqSummary[1,]$n))
print(paste0("Total independent observations where other furbearers were present ", imgDatUSeqSummarySpcs[which(imgDatUSeqSummarySpcs$spcs=="raccoon"),]$n/imgDatUSeqSummary[which(imgDatUSeqSummary$class=="furbearer"),]$n))
print(paste0("Total independent observations where vague ID were present ", imgDatUSeqSummary[3,]$n))


imgDatUSeqPlotor <- imgDatUSeq %>% filter(class == "furbearer") %>% group_by(spcs) %>% summarise(n=n())

print(paste0("Percent independent observations were present P. lotor ", imgDatUSeqPlotor[10,]$n/sum(imgDatUSeqPlotor$n)))
print(paste0("Total independent observations where other furbearers were present ", imgDatUSeqSummary[2,]$n))
print(paste0("Total independent observations where vague ID were present ", imgDatUSeqSummary[3,]$n))

```

```{r summarise imgs by spcs create summary charts for each spcs seen}
imgDatspcs <- imgDat %>% filter(season=="S")%>% group_by(spcs) %>% summarise(n=n())
imgDatspcs2 <- imgDatspcs %>% 
  mutate(per = round(n/sum(n)*100,1))
#theme(axis.text.x = , axis.ticks.x = , axis.text.y = , axis.ticks.y =,legend.title = element_text(size=8),  legend.text = element_text(size=6))
imgDatspcs <- imgDat %>% group_by(spcs) %>% summarise(n=n())
imgDatspcs2 <- imgDatspcs %>% 
  mutate(per = round(n/sum(n)*100,1))
imgDatspcs2 <- imgDatspcs2 %>% select(per, spcs)
plot<-ggplot(imgDatspcs2, aes(x="",y = per,fill=spcs, label=per)) +
  geom_col(position='dodge') + 
     geom_text(position = position_dodge(width = .9),    # move to center of bars
              vjust = -0.5,    # nudge above top of bar
              size = 3)
  plot<-plot+guides(color = guide_legend(override.aes = list(size=4)))
  plot
```

```{r rectify bad datetime}

deployStrings <- unique(S01$deployString)
for(i in 1:length(deployStrings)){
  deploy<-S01 %>% filter(deployString==deployStrings[i]) # filter by the deployment
  S01 <- S01 %>% filter(deployString!=deployStrings[i]) # remove them
  ordrdDeploy <- deploy %>% arrange(date)
  deployDate <- ordrdDeploy[1,]$date
  deploy<-subsetTimeHard(deploy,deployDate=deployDate,
                     imgDateCol="date")
  S01 <- rbind(S01, deploy)
}

```

```{r investigate deer images}

# note remove images for S-S05a-A10-2321; S-S02-A109-1870; S-S02-AO7-548


sites$site <- toupper(sites$site)
sites$season <- toupper(sites$season)
sites$uid <- paste0(sites$season, "-", sites$site, "-", sites$cam, "-", sites$imgNum)
sites$uid <- as.character(sites$uid)
imgDatUSeq$imgIDsplit <- as.character(imgDatUSeq$imgIDsplit)
sites$deployString <- toupper(sites$deployString)
sites$imgIDSplit <- sites$uid
imgDat$useq <- paste0(imgDat$deployString, "-", imgDat$sequenceID)
imgDatDeer <- imgDat %>% filter(class=="deer" & deerOnBothSides==TRUE)
imgDatDeer <- merge(imgDatDeer, sitesSum, on.x="deployString.x", on.y="deployString", all.x=TRUE)
imgDatDeerContactPossible <- imgDatDeer %>% filter(contactPossible==TRUE & contactSeen==FALSE)
imgDatDeerContactSeen <- imgDatDeer %>% filter(contactSeen==TRUE) 

imgDath <- camDat %>% dplyr::select(deployString,deploymentDate)
imgDath <- imgDath %>% filter(!duplicated(deployString))
names(imgDath) <- c("deployString", "deployDate")
sites$deployString <- toupper(sites$deployString)
sites.m <- merge(sites,imgDath, on.x="deployString", on.y="deployString",all.x=TRUE)
# subset time
# get denominators for seasonal comparison
sites <- sites %>% filter(inSamplePeriod==TRUE)
# get number of images
sitesSum <- sites %>% group_by(deployString,season) %>% summarise(n=n())
#write.table(sitesSum, "./data/numImagesSummary")
deployStrings <- unique(sites.m$deployString)
sites.m <- sites.m %>% filter(deployString != "S-S03-A04")
sites.m$deployDate <- if_else(sites.m$deployDate=="",NA,sites.m$deployDate)
sites.m$inSamplePeriod <- FALSE
for(i in 1:length(deployStrings)){
  deploy<-sites.m %>% filter(deployString==deployStrings[i]) # filter by the deployment
  imgDatm <- sites.m %>% filter(deployString!=deployStrings[i]) # remove them
  deploy<-subsetTime(deploy,deployDateCol="deployDate",
                     imgDateCol="date")
  sites.m <- rbind(sites.m, deploy) # rbind the time subset dataframe
}

# filter by useq
imgDatDeerContactPossible<-imgDatDeerContactPossible %>% filter(!duplicated(uSeq))
imgDatDeerContactSeen<-imgDatDeerContactSeen %>% filter(!duplicated(uSeq))

# see proportions of images captured by season
print(paste0("Total images seen where contact possible fall ", length(which(imgDatDeerContactPossible$season.x=='F')), " of ",nrow(imgDatDeerContactPossible)))
#contact possible
print(paste0("Total images seen where contact possible s ", length(which(imgDatDeerContactPossible$season.x=='S')), " of ",nrow(imgDatDeerContactPossible)))
length(which(imgDatDeerContactPossible$season.x=='F'))
print(paste0("Total images seen where contact possible winter ", length(which(imgDatDeerContactPossible$season.x=='F')) , " of ", nrow(imgDatDeerContactPossible)))

sumSeason <- sites %>% filter(!duplicated(deployString.x)) %>% group_by(season.x) %>% summarise(numImages=sum(n))

# contact seen 
print(paste0("Total images seen where contact seen fall ", length(which(imgDatDeerContactSeen$season.x=='F')), " of ",nrow(imgDatDeerContactSeen)))

print(paste0("Total images seen where contact seen winter ", length(which(imgDatDeerContactSeen$season.x=='W')), " of ",nrow(imgDatDeerContactSeen)))

print(paste0("Total images seen where contact seen summer ", length(which(imgDatDeerContactSeen$season.x=='S')), " of ", nrow(imgDatDeerContactSeen)))


length(which(imgDatDeerContactPossible$season.x=='S'))
length(which(imgDatDeerContactPossible$season.x=='W'))
length(which(imgDatDeerContactSeen$season.x=='F'))
length(which(imgDatDeerContactSeen$season.x=='S'))
length(which(imgDatDeerContactSeen$season.x=='W'))
```
```{r summarize field scans}
imgDat$imgID <- paste0(imgDat$season, "-", imgDat$site, "-", imgDat$cam, "-", imgDat$imgNum)
sites$site <- toupper(sites$site)
sites$season <- toupper(sites$season)
sites$uid <- paste0(sites$season, "-", sites$site, "-", sites$cam, "-", sites$imgNum)
sites$uid <- as.character(sites$uid)
imgDatUSeq$imgIDsplit <- as.character(imgDatUSeq$imgIDsplit)
sites$uid <- toupper(sites$uid)
sites$imgIDSplit <- sites$uid
mergedImgDat <- merge(sites, imgDatUSeq, all.x=TRUE, on.x="imgIDSplit", on.y="imgIDSplit") 
mergedImgDat$deployString <- paste0(mergedImgDat$season, "-", mergedImgDat$site, "-", mergedImgDat$cam)
deployStrings<-toupper(unique(mergedImgDat$deployString))
deployStrings <- c(deployStrings, "W-S03-A70", "W-S04-A48", "W-S03-A75")
# create img dat meta with unique deploy strings
imgDatMeta <- mergedImgDat %>% 
distinct(deployString) %>% mutate(numHours = 0, num=0, class="")
imgDatMeta$season <-""
imgDatMeta$site <- ""
imgDatMeta$cam <- ""
for(i in 1:nrow(imgDatMeta)){
  deployString <- strsplit(imgDatMeta[i,]$deployString,"-")[[1]]
  imgDatMeta[i,]$season <- deployString[1]
  imgDatMeta[i,]$site <- deployString[2]
  imgDatMeta[i,]$cam <- deployString[3]
}

imgDatMeta <- imgDatMeta[,c((ncol(imgDatMeta)-2), (ncol(imgDatMeta)-1),ncol(imgDatMeta), 1, 2, 3)]
mergedImgDat$deployString <- toupper(mergedImgDat$deployString)
deployStrings <- toupper(imgDat$deployString)
imgDatMeta$deployString <- toupper(imgDatMeta$deployString)
sites.m <- sites.m %>% filter(deployString != "S-S03-A04")
imgDat$inSamplePeriod <- FALSE
for(i in 1:length(deployStrings)){
  deploy<-imgDat %>% filter(deployString==deployStrings[i]) # filter by the deployment
  mergedImgDat <- imgDat %>% filter(deployString!=deployStrings[i]) # remove them
  deploy<-subsetTime(deploy)
  imgDat <- rbind(imgDat, deploy) # rbind the time subset dataframe
}

sites.m <- sites.m[-c(which(sites.m$site=='S01' & sites.m$season=='S')),]
sites.m <- rbind(sites.m, S01)
# imgDat$encounterID<-0
# createEncounterID<-function(deployDat, encounterCutOff){
#   # first get deployDat in chronological order
#   
#   deployDat <- deployDat %>% filter(class!="")
#   deployDat <- deployDat %>% filter(!is.na(class))
#   deployDat <- deployDat %>% arrange(date)
#   if(nrow(deployDat) > 1){
#     # get all of the unique hours of the deployment
#     hours <-unique(strptime(deploy$date, format="%Y-%m-%d %H"))
#     for(i in 1:length(depoyDat)){
#       # create df of all of the encounters in an hour
#       hour<-deploy[which(strptime(deploy$date, format="%Y-%m-%d %H")==hours[i]),]
#       # grab positives
#       positives <- hour %>% filter(!is.na(imgID))
#       if(nrow(positives) > 1){
#         for(i in 1:nrow(positives)){
#           halfHour <- positives[which()]
#         }
#       }
#       {
#       halfhour <- hour[which(as.numeric(format(hour$date, "%M")) > 30)),]
#       if(abs(difftime(strptime(deployDat[1,]$date, "%Y-%m-%d"), strptime(deployDat[i,]$date, "%Y-%m-%d"), units='days')) > 14 || is.na(deployDat[i,]$date)){
#       badIndx[j] <- i
#       j <- j + 1
#     }
#   }
#     if(length(badIndx)>0){
#       deployDat <- deployDat[-c(badIndx),]
#         }  
#       }
# return(deployDat)
# }

# filter any sequences which don't have corresponding entries from the
mergedImgUSeq <- imgDatUSeq
imgDatm$useq <- paste0(imgDatm$deployString, "-", imgDatm$sequenceID)
mergedImgUSeq <- imgDatm %>% filter(!duplicated(useq))
mergedImgUSeq <- mergedImgDat %>% filter(!is.na(sequenceID))
mergedImgUSeq$site <- toupper(mergedImgUSeq$site)
mergedImgUSeq$deployString <- toupper(mergedImgUSeq$deployString)
mergedImgUSeq$season <- toupper(mergedImgUSeq$season)
imgDatUSeqS <- imgDatUSeq %>% filter(season == "S")
imgDatUSeqInSamp <- imgDatUSeqS %>% filter(inSamplePeriod==TRUE)


# this is the table for summer analysis

write.table(imgDatUSeqInSamp, "./data/inSampSummerDF")
```
```{r}
# get summer deployStrings
deployStrings <- sites.m %>% filter(season=="S") %>% dplyr::select(deployString) %>% filter(!duplicated(deployString),)
deployStrings <- c(deployStrings$deployString) # only want a vector

# make design matrix of each class and deploystring of interest
designMat <- as.data.frame(expand.grid(nobs=0,class=c("deer", "furbearer"), deployString=as.character(deployStrings)))
designMat$camAngle <- 0
designMat$camHeight <- 0
designMat$numHours <- 0
designMat$bearing  <- 0
designMat$wildDeerDens <- 0
designMat$propForest1k <- 0  
designMat$propForest3k<- 0 
designMat$propForest5k <- 0
designMat$numAdults <- 0
designMat$wildDeerDens <- 0
designMat$sizeSqKM <- 0
designMat$type <- ""
designMat$facilitySizeSqMi <- 0
designMat$lsm_l_ai_1k <- 0
designMat$lsm_l_ai_3k <- 0
designMat$lsm_l_ai_5k <- 0
designMat$roadDens1km <- 0
designMat$roadDens3km <- 0
designMat$roadDens5km <- 0
designMat$contactSeen <- 0
designMat$cid <- ""
designMat$sid <- ""
designMat$spcs <- ""
designMat$season <- ""
designMat$cam <- ""
classImg <- mergedImgUSeq[-c(which(mergedImgUSeq$class=="vague ID")),]
designMat$deployString <- as.character(designMat$deployString)

designMat$class <- as.character(designMat$class)

mergedImgUSeq <- imgDatUSeqInSamp %>% group_by(deployString,class) %>% summarise(n=n())


for(j in 1:nrow(mergedImgUSeq)){
    depString<-mergedImgUSeq[j,]$deployString
    currClass <-mergedImgUSeq[j,]$class
    designMatSub<-designMat%>% filter(deployString==depString)
    designMatSub$deployString <- mergedImgUSeq[j,]$deployString
    designMatSubClass <- designMatSub %>% filter(class==currClass)
    if(nrow(designMatSubClass) > 1 || (nrow(designMatSubClass) == 1 & designMatSubClass[1,]$nobs != 0)){
      designMatSubClass<-rbind(designMatSubClass, rep(NA,ncol(designMat)))
      designMatSubClass[nrow(designMatSubClass),]$nobs <- mergedImgUSeq[j,]$numInds
      designMatSubClass[nrow(designMatSubClass),]$class <- mergedImgUSeq[j,]$class
      designMatSubClass[nrow(designMatSubClass),]$spcs <- mergedImgUSeq[j,]$spcs
    }
    if((nrow(designMatSubClass) == 1) & (designMatSubClass[1,]$nobs == 0)){
      designMatSubClass[1,]$nobs <- mergedImgUSeq[j,]$numInds
      designMatSubClass[1,]$class <- mergedImgUSeq[j,]$class
      designMatSubClass[1,]$spcs <- mergedImgUSeq[j,]$spcs
    }
      designMatSub <- designMatSub[-c(which(designMatSub$class==currClass)),]
      designMatSub <- rbind(designMatSub,designMatSubClass)
      designMatSub$deployString <- mergedImgUSeq[j,]$deployString
      designMatSub$season <- mergedImgUSeq[j,]$season
      designMatSub$sid <- mergedImgUSeq[j,]$site
      designMatSub$cid <- mergedImgUSeq[j,]$cam
      designMatSub$deployString <- mergedImgUSeq[j,]$deployString
      designMat<- designMat[-c(which(designMat$deployString == depString)),]
      designMat <- rbind(designMat, designMatSub)
}
# this converts from factor to character
depStrings <- as.character(designMat$deployString)
designMat$deployString <- depStrings
c<-as.character(designMat$class)
designMat$class <- c
# split to get sid cam
for(i in 1:nrow(designMat)){
season<-strsplit(designMat[i,]$deployString, "-")[[1]][1]
site<-strsplit(designMat[i,]$deployString, "-")[[1]][2]
cam<-strsplit(designMat[i,]$deployString, "-")[[1]][3]
designMat[i,]$season <- season
designMat[i,]$sid <- site
designMat[i,]$cid <- cam
}


# prepare unique sequence dataframe for merging into designMat 
camDat$deployString <- toupper(paste0(camDat$season,"-",camDat$sid, "-",camDat$cid))
propForestDat$sid <- toupper(propForestDat$sid)
siteCovariates$Site.ID <- toupper(siteCovariates$Site.ID)
farmSizedf$farm_id <- toupper(farmSizedf$farm_id)
designMat$site <- toupper(designMat$site)
lsmDat$sid <- toupper(lsmDat$sid)
for(i in 1:nrow(designMat)){
  # camera specific covariates
  
  
  # sites-specific covariates
  designMat[i,]$propForest1k <- propForestDat[which(propForestDat$sid == designMat[i,]$sid),]$propForest1k
  designMat[i,]$propForest3k <- propForestDat[which(propForestDat$sid == designMat[i,]$sid),]$propForest3k
  designMat[i,]$propForest5k <- propForestDat[which(propForestDat$sid == designMat[i,]$sid),]$propForest5k
  if(designMat[i,]$deployString %in% camDat$deployString){
  designMat[i,]$camAngle <- camDat[which(camDat$deployString==designMat[i,]$deployString),]$cameraAngle
   designMat[i,]$camHeight <- camDat[which(camDat$deployString==designMat[i,]$deployString),]$groundDist
   designMat[i,]$bearing <- camDat[which(camDat$deployString==designMat[i,]$deployString),]$bearing
  }
  if(designMat[i,]$deployString %in% imgDatMeta$deployString){
    designMat[i,]$numHours <- imgDatMeta[which(imgDatMeta$deployString == designMat[i,]$deployString),]$numHours
  }
   designMat[i,]$wildDeerDens <- siteCovariates[which(siteCovariates$Site.ID==designMat[i,]$sid),]$Deer_Density_SqMi
   designMat[i,]$type <- siteCovariates[which(siteCovariates$Site.ID==designMat[i,]$sid),]$Type
   designMat[i,]$residence <- siteCovariates[which(siteCovariates$Site.ID==designMat[i,]$sid),]$Residence
   designMat[i,]$numAdults <- siteCovariates[which(siteCovariates$Site.ID==designMat[i,]$sid),]$numAdults
   designMat[i,]$facilitySizeSqMi <- farmSizedf[which(farmSizedf$farm_id==designMat[i,]$sid),]$sizemi2
   # load landscape metrics
    designMat[i,]$lsm_l_ai_1k <- lsmDat[which(lsmDat$sid==designMat[i,]$sid),]$lsm_l_ai_1k
    designMat[i,]$lsm_l_ai_3k <- lsmDat[which(lsmDat$sid==designMat[i,]$sid),]$lsm_l_ai_3k
    designMat[i,]$lsm_l_ai_5k <- lsmDat[which(lsmDat$sid==designMat[i,]$sid),]$lsm_l_ai_5k
}


for(i in 1:nrow(designMat2)){
if(designMat2[i,]$deployString %in% camDat$deployString){
    designMat2[i,]$camAngle <- camDat[which(camDat$deployString==designMat2[i,]$deployString),]$cameraAngle
    designMat2[i,]$camHeight <- camDat[which(camDat$deployString==designMat2[i,]$deployString),]$groundDist
    designMat2[i,]$bearing <- camDat[which(camDat$deployString==designMat2[i,]$deployString),]$bearing
  }
  if(designMat2[i,]$deployString %in% imgDatMeta$deployString){
    designMat2[i,]$numHours <- imgDatMeta[which(imgDatMeta$deployString == designMat2[i,]$deployString),]$numHours
  }
  designMat2[i,]$wildDeerDens <- siteCovariates[which(siteCovariates$Site.ID==designMat2[i,]$sid),]$Deer_Density_SqMi
  designMat2[i,]$type <- siteCovariates[which(siteCovariates$Site.ID==designMat2[i,]$sid),]$Type
  designMat2[i,]$residence <- siteCovariates[which(siteCovariates$Site.ID==designMat2[i,]$sid),]$Residence
  designMat2[i,]$numAdults <- siteCovariates[which(siteCovariates$Site.ID==designMat2[i,]$sid),]$numAdults
  designMat2[i,]$facilitySizeSqMi <- farmSizedf[which(farmSizedf$farm_id==designMat2[i,]$sid),]$sizemi2
  # load landscape metrics
  designMat2[i,]$lsm_l_ai_1k <- lsmDat[which(lsmDat$sid==designMat2[i,]$sid),]$lsm_l_ai_1k
  designMat2[i,]$lsm_l_ai_3k <- lsmDat[which(lsmDat$sid==designMat2[i,]$sid),]$lsm_l_ai_3k
  designMat2[i,]$lsm_l_ai_5k <- lsmDat[which(lsmDat$sid==designMat2[i,]$sid),]$lsm_l_ai_5k
}



# build second design mat

write.table(designMat,"./data/designMat")
write.table(designMat2,"./data/designMat2")
designMat2<-read.table("./data/designMat2")
designMat2<-read.table("./data/designMat")
designMat <- designMat[-c(which(designMat$deployString %in% feederDeploys)),]
designMatS<-read.table("./data/designMat")


designMat2$roadDens1km <- 0
designMat2$roadDens3km <- 0
designMat2$roadDens5km <- 0
roadDensDat$sid <- toupper(roadDensDat$sid)
for(i in 1:nrow(designMat2)){
    designMat2[i,]$roadDens1km <- roadDensDat[which(roadDensDat$sid == designMat2[i,]$sid),]$roadDens1km
    designMat2[i,]$roadDens3km <- roadDensDat[which(roadDensDat$sid == designMat2[i,]$sid),]$roadDens3km
    designMat2[i,]$roadDens5km <- roadDensDat[which(roadDensDat$sid == designMat2[i,]$sid),]$roadDens5km
}
imgDat <- imgDat %>% filter(inSamplePeriod==TRUE)
furbearer <- imgDat %>% filter(class == "furbearer")
deer<- imgDat %>% filter(class == "deer")
plotor <- imgDat %>% filter(spcs %in% c("raccoon","skunk","possum"))
plotor <- plotor %>% group_by(deployString.x) %>% summarise(n=n())
furbearer <- furbearer %>% group_by(deployString.x) %>% summarise(n=n())
deer <- deer %>% group_by(deployString.x) %>% summarise(n=n())
designMatPlotor$nobs <- 0
designMatF$nobs <- 0
designMatD$nobs <- 0

deployStringPlotor <- unique(plotor$deployString.x)
deployStringD <- unique(deer$deployString.x)
deployStringF <- unique(furbearer$deployString.x)
for(i in 1:length(deployStringD)){
  designMatD[which(designMatD$deployString==deployStringD[i]),]$nobs <- deer[which(deer$deployString.x == deployStringD[i]),]$n 
}
for(i in 1:length(deployStringF)){
  designMatF[which(designMatF$deployString==deployStringF[i]),]$nobs <- furbearer[which(furbearer$deployString.x==deployStringF[i]),]$n 
}
for(i in 1:length(deployStringPlotor)){
  designMatPlotor[which(designMatPlotor$deployString==deployStringPlotor[i]),]$nobs <- plotor[which(plotor$deployString.x==deployStringPlotor[i]),]$n 
}


sid <- unique(lsmDat2$sid)
designMatD$lsm_l_shdi_1k <- 0
designMatD$lsm_l_shdi_3k <- 0
designMatD$lsm_l_shdi_5k <- 0
designMatF$lsm_l_shdi_1k <- 0
designMatF$lsm_l_shdi_3k <- 0
designMatF$lsm_l_shdi_5k <- 0
designMatPlotor$lsm_l_shdi_1k <- 0
designMatPlotor$lsm_l_shdi_3k <- 0
designMatPlotor$lsm_l_shdi_5k <- 0
#prop Dev
designMatD$propDev1k <- 0
designMatD$propDev3k <- 0
designMatD$propDev5k <- 0
designMatF$propDev1k <- 0
designMatF$propDev3k <- 0
designMatF$propDev5k <- 0
designMatPlotor$propDev1k <- 0
designMatPlotor$propDev3k <- 0
designMatPlotor$propDev5k <- 0
#prop ag
designMatD$propAg1k <- 0
designMatD$propAg3k <- 0
designMatD$propAg5k <- 0
designMatF$propAg1k <- 0
designMatF$propAg3k <- 0
designMatF$propAg5k <- 0
designMatPlotor$propAg1k <- 0
designMatPlotor$propAg3k <- 0
designMatPlotor$propAg5k <- 0
#road density
designMatD$roadDens1km <- 0
designMatD$roadDens3km <- 0
designMatD$roadDens5km <- 0
designMatF$roadDens1km <- 0
designMatF$roadDens3km <- 0
designMatF$roadDens5km <- 0
designMatPlotor$roadDens1km <- 0
designMatPlotor$roadDens3km <- 0
designMatPlotor$roadDens5km <- 0

for(i in 1:length(sid)){
  designMatD[which(designMatD$sid==sid[i]),]$propAg1k <- lcDat[which(lcDat$sid==sid[i]),]$propAg1k
  designMatD[which(designMatD$sid==sid[i]),]$propAg3k <- lcDat[which(lcDat$sid==sid[i]),]$propAg3k
  designMatD[which(designMatD$sid==sid[i]),]$propAg5k <- lcDat[which(lcDat$sid==sid[i]),]$propAg5k
  designMatF[which(designMatF$sid==sid[i]),]$propAg1k <- lcDat[which(lcDat$sid==sid[i]),]$propAg1k
  designMatF[which(designMatF$sid==sid[i]),]$propAg3k <- lcDat[which(lcDat$sid==sid[i]),]$propAg3k
  designMatF[which(designMatF$sid==sid[i]),]$propAg5k <- lcDat[which(lcDat$sid==sid[i]),]$propAg5k
    designMatPlotor[which(designMatPlotor$sid==sid[i]),]$propAg1k <- lcDat[which(lcDat$sid==sid[i]),]$propAg1k
  designMatPlotor[which(designMatPlotor$sid==sid[i]),]$propAg3k <- lcDat[which(lcDat$sid==sid[i]),]$propAg3k
  designMatPlotor[which(designMatPlotor$sid==sid[i]),]$propAg5k <- lcDat[which(lcDat$sid==sid[i]),]$propAg5k
  # dev
    designMatD[which(designMatD$sid==sid[i]),]$propDev1k <- lcDat[which(lcDat$sid==sid[i]),]$propDev1k
  designMatD[which(designMatD$sid==sid[i]),]$propDev3k <- lcDat[which(lcDat$sid==sid[i]),]$propDev3k
  designMatD[which(designMatD$sid==sid[i]),]$propDev5k <- lcDat[which(lcDat$sid==sid[i]),]$propDev5k
  designMatF[which(designMatF$sid==sid[i]),]$propDev1k <- lcDat[which(lcDat$sid==sid[i]),]$propDev1k
  designMatF[which(designMatF$sid==sid[i]),]$propDev3k <- lcDat[which(lcDat$sid==sid[i]),]$propDev3k
  designMatF[which(designMatF$sid==sid[i]),]$propDev5k <- lcDat[which(lcDat$sid==sid[i]),]$propDev5k
    designMatPlotor[which(designMatPlotor$sid==sid[i]),]$propDev1k <- lcDat[which(lcDat$sid==sid[i]),]$propDev1k
  designMatPlotor[which(designMatPlotor$sid==sid[i]),]$propDev3k <- lcDat[which(lcDat$sid==sid[i]),]$propDev3k
  designMatPlotor[which(designMatPlotor$sid==sid[i]),]$propDev5k <- lcDat[which(lcDat$sid==sid[i]),]$propDev5k
  #lsm Dat
  designMatD[which(designMatD$sid==sid[i]),]$lsm_l_shdi_1k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_1k
designMatD[which(designMatD$sid==sid[i]),]$lsm_l_shdi_3k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_3k
designMatD[which(designMatD$sid==sid[i]),]$lsm_l_shdi_5k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_5k
designMatF[which(designMatF$sid==sid[i]),]$lsm_l_shdi_1k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_1k
designMatF[which(designMatF$sid==sid[i]),]$lsm_l_shdi_3k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_3k
designMatF[which(designMatF$sid==sid[i]),]$lsm_l_shdi_5k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_5k
designMatPlotor[which(designMatPlotor$sid==sid[i]),]$lsm_l_shdi_1k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_1k
designMatPlotor[which(designMatPlotor$sid==sid[i]),]$lsm_l_shdi_3k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_3k
designMatPlotor[which(designMatPlotor$sid==sid[i]),]$lsm_l_shdi_5k <- lsmDat[which(lsmDat$sid==sid[i]),]$lsm_l_shdi_5k
}
for(i in 1:length(sid)){
designMatD[which(designMatD$sid==sid[i]),]$roadDens1km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens1km
designMatD[which(designMatD$sid==sid[i]),]$roadDens3km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens3km
designMatD[which(designMatD$sid==sid[i]),]$roadDens5km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens5km
designMatF[which(designMatF$sid==sid[i]),]$roadDens1km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens1km
designMatF[which(designMatF$sid==sid[i]),]$roadDens3km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens3km
designMatF[which(designMatF$sid==sid[i]),]$roadDens5km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens5km
designMatPlotor[which(designMatPlotor$sid==sid[i]),]$roadDens1km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens1km
designMatPlotor[which(designMatPlotor$sid==sid[i]),]$roadDens3km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens3km
designMatPlotor[which(designMatPlotor$sid==sid[i]),]$roadDens5km <- roadDensDat[which(roadDensDat$sid==sid[i]),]$roadDens5km
}
#lsm_l_ai
designMatD$lsm_l_ai_1k.sc <- scale(designMatD$lsm_l_ai_1k)[,1]
designMatD$lsm_l_ai_3k.sc <- scale(designMatD$lsm_l_ai_3k)[,1]
designMatD$lsm_l_ai_5k.sc <- scale(designMatD$lsm_l_ai_5k)[,1]
designMatF$lsm_l_ai_1k.sc <- scale(designMatF$lsm_l_ai_1k)[,1]
designMatF$lsm_l_ai_3k.sc <- scale(designMatF$lsm_l_ai_3k)[,1]
designMatF$lsm_l_ai_5k.sc <- scale(designMatF$lsm_l_ai_5k)[,1]
designMatPlotor$lsm_l_ai_1k.sc <- scale(designMatPlotor$lsm_l_ai_1k)[,1]
designMatPlotor$lsm_l_ai_3k.sc <- scale(designMatPlotor$lsm_l_ai_3k)[,1]
designMatPlotor$lsm_l_ai_5k.sc <- scale(designMatPlotor$lsm_l_ai_5k)[,1]
#lsm_l_shdi
designMatD$lsm_l_shdi_1k.sc <- scale(designMatD$lsm_l_shdi_1k)[,1]
designMatD$lsm_l_shdi_3k.sc <- scale(designMatD$lsm_l_shdi_3k)[,1]
designMatD$lsm_l_shdi_5k.sc <- scale(designMatD$lsm_l_shdi_5k)[,1]
designMatF$lsm_l_shdi_1k.sc <- scale(designMatF$lsm_l_shdi_1k)[,1]
designMatF$lsm_l_shdi_3k.sc <- scale(designMatF$lsm_l_shdi_3k)[,1]
designMatF$lsm_l_shdi_5k.sc <- scale(designMatF$lsm_l_shdi_5k)[,1]
designMatPlotor$lsm_l_shdi_1k.sc <- scale(designMatPlotor$lsm_l_shdi_1k)[,1]
designMatPlotor$lsm_l_shdi_3k.sc <- scale(designMatPlotor$lsm_l_shdi_3k)[,1]
designMatPlotor$lsm_l_shdi_5k.sc <- scale(designMatPlotor$lsm_l_shdi_5k)[,1]
# ag
designMatD$propAg1k.sc <- scale(designMatD$propAg1k)[,1]
designMatD$propAg3k.sc <- scale(designMatD$propAg3k)[,1]
designMatD$propAg5k.sc <- scale(designMatD$propAg5k)[,1]
designMatF$propAg1k.sc <- scale(designMatF$propAg1k)[,1]
designMatF$propAg3k.sc <- scale(designMatF$propAg3k)[,1]
designMatF$propAg5k.sc <- scale(designMatF$propAg5k)[,1]
designMatPlotor$propAg1k.sc <- scale(designMatPlotor$propAg1k)[,1]
designMatPlotor$propAg3k.sc <- scale(designMatPlotor$propAg3k)[,1]
designMatPlotor$propAg5k.sc <- scale(designMatPlotor$propAg5k)[,1]
# dev
designMatD$propDev1k.sc <- scale(designMatD$propDev1k)[,1]
designMatD$propDev3k.sc <- scale(designMatD$propDev3k)[,1]
designMatD$propDev5k.sc <- scale(designMatD$propDev5k)[,1]
designMatF$propDev1k.sc <- scale(designMatF$propDev1k)[,1]
designMatF$propDev3k.sc <- scale(designMatF$propDev3k)[,1]
designMatF$propDev5k.sc <- scale(designMatF$propDev5k)[,1]
designMatPlotor$propDev1k.sc <- scale(designMatPlotor$propDev1k)[,1]
designMatPlotor$propDev3k.sc <- scale(designMatPlotor$propDev3k)[,1]
designMatPlotor$propDev5k.sc <- scale(designMatPlotor$propDev5k)[,1]
#forest
designMatD$propForest1k.sc <- scale(designMatD$propForest1k)[,1]
designMatD$propForest3k.sc <- scale(designMatD$propForest3k)[,1]
designMatD$propForest5k.sc <- scale(designMatD$propForest5k)[,1]
designMatF$propForest1k.sc <- scale(designMatF$propForest1k)[,1]
designMatF$propForest3k.sc <- scale(designMatF$propForest3k)[,1]
designMatF$propForest5k.sc <- scale(designMatF$propForest5k)[,1]
designMatPlotor$propForest1k.sc <- scale(designMatPlotor$propForest1k)[,1]
designMatPlotor$propForest3k.sc <- scale(designMatPlotor$propForest3k)[,1]
designMatPlotor$propForest5k.sc <- scale(designMatPlotor$propForest5k)[,1]
# roadDens
designMatD$roadDens1km.sc <- scale(designMatD$roadDens1km)[,1]
designMatD$roadDens3km.sc <- scale(designMatD$roadDens3km)[,1]
designMatD$roadDens5km.sc <- scale(designMatD$roadDens5km)[,1]
designMatF$roadDens1km.sc <- scale(designMatF$roadDens1km)[,1]
designMatF$roadDens3km.sc <- scale(designMatF$roadDens3km)[,1]
designMatF$roadDens5km.sc <- scale(designMatF$roadDens5km)[,1]
designMatPlotor$roadDens1km.sc <- scale(designMatPlotor$roadDens1km)[,1]
designMatPlotor$roadDens3km.sc <- scale(designMatPlotor$roadDens3km)[,1]
designMatPlotor$roadDens5km.sc <- scale(designMatPlotor$roadDens5km)[,1]
#wild deer Dens
designMatD$wildDeerDens.sc <- scale(designMatD$wildDeerDens)[,1]
designMatF$wildDeerDens.sc <- scale(designMatF$wildDeerDens)[,1]
designMatPlotor$wildDeerDens.sc <- scale(designMatPlotor$wildDeerDens)[,1]
# captive Deer Dens
designMatD <- designMatD %>% mutate(captiveDeerDens = (numAdults/facilitySizeSqMi) * (1/(2.59*10^6)))
designMatF <- designMatF %>% mutate(captiveDeerDens = (numAdults/facilitySizeSqMi) * (1/(2.59*10^6)))
designMatPlotor <- designMatPlotor %>% mutate(captiveDeerDens = (numAdults/facilitySizeSqMi) * (1/(2.59*10^6)))
#scale result
designMatD$captiveDeerDens.sc <- scale(designMatD$captiveDeerDens)[,1]
designMatF$captiveDeerDens.sc <- scale(designMatF$captiveDeerDens)[,1]
designMatPlotor$captiveDeerDens.sc <- scale(designMatPlotor$captiveDeerDens)[,1]
#scale num Hours
designMatD[which(designMatD$deployString=="S-S01-A16"),]$numHours <- 218
designMatD[which(designMatD$deployString=="S-S04-A80"),]$numHours <- 340
designMatD[which(designMatD$deployString=="S-S04-A04"),]$numHours <- 17.41

designMatF[which(designMatF$deployString=="S-S01-A16"),]$numHours <- 218
designMatF[which(designMatF$deployString=="S-S04-A80"),]$numHours <- 340
designMatF[which(designMatF$deployString=="S-S04-A04"),]$numHours <- 17.41

designMatPlotor[which(designMatPlotor$deployString=="S-S01-A16"),]$numHours <- 218
designMatPlotor[which(designMatPlotor$deployString=="S-S04-A80"),]$numHours <- 340
designMatPlotor[which(designMatPlotor$deployString=="S-S04-A04"),]$numHours <- 17.41
designMatD$numHours.sc <- scale(designMatD$numHours)[,1]
designMatF$numHours.sc <- scale(designMatF$numHours)[,1]
designMatPlotor$numHours.sc <- scale(designMatPlotor$numHours)[,1]
# scale camHeight
designMatD$camHeight.sc <- scale(designMatD$camHeight)[,1]
designMatF$camHeight.sc <- scale(designMatF$camHeight)[,1]
designMatPlotor$camHeight.sc <- scale(designMatPlotor$camHeight)[,1]
# scale camAngle
designMatD$camAngle.sc <- scale(designMatD$camAngle)[,1]
designMatF$camAngle.sc <- scale(designMatF$camAngle)[,1]
designMatPlotor$camAngle.sc <- scale(designMatPlotor$camAngle)[,1]

# get the number of cameras
numCam <- designMatF %>% group_by(season,sid) %>% summarise(n=n())
numCam$seasonDep <- paste0(numCam$season,"-",numCam$sid)
designMatF$seasonDep <- paste0(designMatF$season,"-",designMatF$sid)
designMatD$seasonDep <- paste0(designMatD$season,"-",designMatD$sid)
designMatPlotor$seasonDep <- paste0(designMatPlotor$season,"-",designMatPlotor$sid)
designMatD$numCam <- 0
designMatF$numCam <- 0
designMatPlotor$numCam <- 0
for(i in 1:nrow(numCam)){
designMatD[which(designMatD$seasonDep==numCam[i,]$seasonDep),]$numCam <- numCam[i,]$n
designMatF[which(designMatF$seasonDep==numCam[i,]$seasonDep),]$numCam <- numCam[i,]$n
designMatPlotor[which(designMatPlotor$seasonDep==numCam[i,]$seasonDep),]$numCam <- numCam[i,]$n
}

designMatD$numCam.sc <- scale(designMatD$numCam)[,1]
designMatF$numCam.sc <- scale(designMatF$numCam)[,1]
designMatPlotor$numCam.sc <- scale(designMatPlotor$numCam)[,1]

# make proportional number of hours which will account for both the number of
# cameras on site and the number of hours that and individual camera was active
designMatF <- designMatF %>% group_by(seasonDep) %>% mutate(camEffort=numHours/sum(numHours))
designMatD <- designMatD %>% group_by(seasonDep) %>% mutate(camEffort=numHours/sum(numHours))
designMatPlotor <- designMatPlotor %>% group_by(seasonDep) %>% mutate(camEffort=numHours/sum(numHours))
# scale these

designMatD$camEffort.sc <- scale(designMatD$camEffort)[,1]
designMatF$camEffort.sc <- scale(designMatF$camEffort)[,1]
designMatPlotor$camEffort.sc <- scale(designMatPlotor$camEffort)[,1]
# these tables contain scaled and unscaled versions of covariates
#read.table(designMatF,"./data/designMatF") # save tables
# write.table(designMatD,"./data/designMatD") # save tables
# write.table(designMatPlotor,"./data/designMatPlotor") # save tables

designMatD<-read.table("./data/designMatD")
designMatF<-read.table("./data/designMatF")
designMatF[which(designMatF$deployString=="")]

# 
# numRow <- nrow(fieldScanMeta)/2
# for(i in 1:numRow){
#   fieldScanMeta[i,]$class <- "deer"
# }
# for(j in (numRow+1):nrow(fieldScanMeta)){
#   fieldScanMeta[j,]$class <- "furbearer"
# }
# #deployStrings <- c(deployStrings, deployStrings)
# for(i in 1:length(deployStrings)){
#   deploy = mergedfieldScan[which(imgDatMeta[i,]$deployString == mergedImgDat$deployString),]
# 
#   
# }
# fieldScanMeta$season <- ""
# fieldScanMeta$site <- ""
# fieldScanMeta$cam <- ""
# fieldScanMeta$rate <- 0
# for(i in 1:nrow(fieldScanMeta)){
#   uidArray<-strsplit(fieldScanMeta[i,]$deployString, "-")[[1]]
#   fieldScanMeta[i,]$season <-uidArray[1]
#   fieldScanMeta[i,]$site <-uidArray[2]
#   fieldScanMeta[i,]$cam <-uidArray[3]
#   if(!is.na(fieldScanMeta[i,]$numHours) & fieldScanMeta[i,]$numHours > 0){
#     fieldScanMeta[i,]$rate <- fieldScanMeta[i,]$num/fieldScanMeta[i,]$numHours
#   }
# }
# #write.table(fieldScanMeta, "./data/fieldscanMeta") # save table
# fieldScanMeta <- fieldScanMeta[-c(which(fieldScanMeta$numHours==0)),]
# fieldScanMeta <- fieldScanMeta[-c(which(fieldScanMeta$site=="")),]
```
```{r merge tables}
names(imgMetaDat) <- c("uuid", "num", "class", "loc", "spcs","note")
# remove first row
imgMetaDat <- imgMetaDat[-1,]
# filter thru all of the inside data
# imgMetaDat <- data.frame(uid=imgDat$uid,num=imgDat$num, class=imgDat$class,
#                     loc=imgDat$loc,spcs=imgDat$spcs, note=imgDat$note)
# subset our data
imgMetaDat <- subset(imgMetaDat, loc != "I" & class != "deer")
imgMetaDat <- subset(imgMetaDat, class != "bird")
imgMetaDatAgg <- as.data.frame(imgDat %>% group_by(uid, class) %>% count())
for(i in 1:nrow(imgMetaDat)){
  # strip away the .JPG suffix; if there is one
  if(grepl(".JPG", imgMetaDat[i,]$uid)){
    imgMetaDat[i,]$uuid <- strsplit(imgMetaDat[i,]$uuid, "\\.")[[1]][1]
  } 
}

imgMetaDat <- subset(imgMetaDat,imgMetaDat$uuid == imgDat$uid)
imgDatMain <- merge(imgDat, imgMetaDat, by.x='uid', by.y='uuid')


```
```{r rate by site}

designMat <- read.table("./data/designMat2")
feeders <- unique(camDat %>% filter(feeder==TRUE) %>% dplyr::select(deployString))
# filter out feeders
designMat <- designMat %>% filter(!deployString %in% feeders)

designMat <- designMat %>% mutate(captiveDeerDens = (numAdults/facilitySizeSqMi) * (1/(2.59*10^6)))


designMat2S <- designMat %>% filter(season=="S") %>% filter(!is.na(camHeight)) %>% filter(!is.na(camAngle))
designMatS <- designMat %>% filter(season=="S") %>% filter(!is.na(camHeight)) %>% filter(!is.na(camAngle))

designMat[which(designMat$deployString=="S-S01-A16"),]$numHours <- 218
designMat[which(designMat$deployString=="S-S04-A80"),]$numHours <- 340
designMat[which(designMat$deployString=="S-S04-A04"),]$numHours <- 17.41


# use this to get the rate by site
siteSummaryObs<- imgDatUSeq %>% filter(season=='S') %>% group_by(deployString, sid, class) %>% summarise(encounterRate = nobs/numHours, ".groups" = "drop") %>% pivot_wider(id_cols = "site")

siteSummaryObs <- siteSummaryObs %>% pivot_wider(id_cols = sid, names_from=class, values_from=avgEncRate)

siteSummaryObs <- siteSummaryObs %>% group_by(sid,class) %>% summarise(avgEncRate=mean(encounterRate,na.rm=TRUE), ".groups" = "drop")
siteSummaryObs %>% melt(id.var="sid")
write.table(siteSummaryObs,"./data/siteSummary", sep=",")


```
```{r create plot to summarise obs}

```

```{r GLM}




designMatS$class.fac <- as.factor(designMatS$class)
designMat <- designMat %>% mutate(captiveDeerDens = (numAdults/facilitySizeSqMi) * (1/(2.59*10^6)))
designMat2 <- designMat2 %>% mutate(captiveDeerDens = (numAdults/facilitySizeSqMi) * (1/(2.59*10^6)))
designMat$captiveDeerDens <- scale(designMat$captiveDeerDens)[,1]
designMat2$captiveDeerDens <- scale(designMat2$captiveDeerDens)[,1]

designMatS$site.fac <- as.factor(designMatS$site)

designMatS <- designMat %>% filter(season=="S") %>% filter(class!="vague ID")
designMat2F <- designMat2 %>% filter(season=="S") %>% filter(class!="vague ID") %>% filter(class=="furbearer")
designMat2D <- designMat2 %>% filter(season=="S") %>% filter(class!="vague ID") %>% filter(class=="deer")
 
designMat2S <- designMat2 %>% filter(season=="S") %>% filter(class!="vague ID")
designMatS <- designMatS[-c(which(is.na(designMatS))),]
designMat2S <- designMat2S[-c(which(is.na(designMat2S))),]
designMatSF <- designMatS %>% filter(class=="furbearer")
designMatSD <- designMatS %>% filter(class=="deer")
designMat2SF <- designMat2S %>% filter(class=="furbearer")
designMat2SD <- designMat2S %>% filter(class=="deer")

designMat3F <- designMat2SF %>% drop_na()
designMat3D <- designMat2SD[1:174,]


# remove malfunctioning cameras; update number of active hours 3/30

designMatF <- designMatF %>% filter(! deployString %in% feeders)
designMatD <- designMatD %>% filter(! deployString %in% feeders)

designMatF <- designMatF %>% filter(! deployString %in% "S-S03-A04")
designMatD <- designMatD %>% filter(! deployString %in% "S-S03-A04")

designMatF[which(designMatF$deployString=="S-S01-A16"),]$numHours <- 218
designMatF[which(designMatF$deployString=="S-S04-A80"),]$numHours <- 340
designMatF[which(designMatF$deployString=="S-S04-A04"),]$numHours <- 17.41


designMatD[which(designMatD$deployString=="S-S01-A16"),]$numHours <- 218
designMatD[which(designMatD$deployString=="S-S04-A80"),]$numHours <- 340
designMatD[which(designMatD$deployString=="S-S04-A04"),]$numHours <- 17.41

designMatD[which(designMatD$deployString=="S-S02-A15"),]$numHours <- 50.664
designMatF[which(designMatF$deployString=="S-S02-A15"),]$numHours <- 50.664

designMatF <- designMatF %>% filter(! deployString %in% "S-S07-A95")
designMatD <- designMatD %>% filter(! deployString %in% "S-S07-A95")

```

```{r filter to summer season}
designMatF <- designMatF %>% filter(season=='S')
designMatD <- designMatD %>% filter(season=='S')
designMatPlotor <- designMatPlotor %>% filter(season=='S')
```

```{r models for deer}
nbModD.1<-glmer.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + numCam.sc + numHours.sc + I(lc.fac==41) + I(lc.fac==81) + (1|sid), data=designMatD)
summary(nbModD.1)
nbModD.2<-glmer.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + lsm_l_ai_5k.sc + numHours.sc +(1|sid),data=designMatD)
summary(nbModD.2)
nbModD.3<-glmer.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + lsm_l_ai_5k.sc + numHours.sc + camEffort.sc + (1|sid),data=designMatD)
summary(nbModD.3)
nbModD.4<-glm.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + numHours.sc + propAg5k.sc + camEffort.sc,data=designMatD)
summary(nbModD.4)

nbModD.5<-glm.nb(nobs ~ camHeight.sc + lsm_l_ai_5k.sc + numHours.sc + propAg5k.sc + camEffort.sc,data=designMatD)
summary(nbModD.5)


nbModD.6<-glm.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + numHours.sc + propAg5k.sc + camEffort.sc,data=designMatD)
summary(nbModD.6)

nbModD.7<-glm.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + numHours.sc + propAg5k.sc,data=designMatD)

nbModD.forest<-glm.nb(nobs ~ camHeight.sc + propForest1k.sc+ lsm_l_shdi_5k.sc + numHours.sc + propAg5k.sc,data=designMatD)

nbModD.forest2<-glm.nb(nobs ~ camHeight.sc + propForest1k.sc + lsm_l_shdi_5k.sc + numHours.sc + propAg3k.sc,data=designMatD)

nbModD.forestDev<-glm.nb(nobs ~ camHeight.sc + propAg5k.sc + I(lc.fac=="41") + I(lc.fac=="81") + lsm_l_shdi_5k.sc + numHours.sc,data=designMatD)
summary(nbModD.forestDev)

nbModD.forest.effort<-glm.nb(nobs ~ camHeight.sc + lsm_l_shdi_5k.sc + propAg5k.sc + numCam.sc + numHours.sc,data=designMatD)
AIC(nbModD.4,nbModD.5,nbModD.6,nbModD.7,nbModD.forest,nbModD.forestDev,nbModD.forest.effort)
summary(nbModD.forest)


# print tab model
tab_model(nbModD.1, pred.labels = c("Intercept", "Camera Height", "Shannon's Diversity Index (5km)", "Number of Cameras", "Number of Hours", "Camera Location (41)", "Camera Location (81)"), title="Regression Results for Wild WTD", transform = NULL,file="./data/regression-deer.html")
# save to png
webshot("./data/regression-deer.html", "./data/regression-deer.png")

```

```{r models for furbearers}

# TOP MODEL
nbModF.1.shdi<-glm.nb(nobs ~ numCam.sc + I(lc.fac==81) + lsm_l_shdi_5k.sc + propAg3k.sc + numHours.sc,data=designMatF)

# try with random effects
nbModF.1.shdi.re<-glmer.nb(nobs ~ numCam.sc + propAg3k.sc + numHours.sc + (1|sid),data=designMatF)

# responded most to propAg at 3km scale

tab_model(nbModF.1.shdi.re, pred.labels = c("Intercept", "Number of Cameras", "Proportion Agriculture (3km)", "Number of Hours"), title="Regression Results for Scavengers", transform = NULL,file="./data/regression-scavengers.html")
# save to png
webshot("./data/regression-scavengers.html", "./data/regression-scavengers.png")

```
```{r create plots for types of landscape sampled}
lcType.dat <- data.frame(val = unique(sort(designMatD$val)), type=c("Developed, Open Space (21)", "Developed, Low Intensity (22)", "Developed Medium Intensity (23)", "Barren (31)", "Deciduous Forest (41)", "Evergreen Forest (42)", "Mixed Forest (43)", "Grassland/Herbaceous (71)", "Pasture/Hay (81)", "Cultivated Crops (82)", "Woody Wetlands (90)", "Emergent Herbaceous Wetlands (95)"))
write.table(lcType.dat, "./data/lcTypeDat") # this holds the df for all of the data types seen

lcTypetmp <- designMatD %>% dplyr::select(val)
lcType.dat <- merge(lcType.dat, lcTypetmp, on.x=val, on.y=val) # merge


lcTypeSummary <- lcType.dat %>% group_by(type) %>% summarise(n=n())
description<-c()
lcTypeSummary$description <- description

ggplot(lcType.dat, aes(x=type)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle=90, hjust=1)) +
  ggtitle(label="Number of Samples of Each Cover Type Taken") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),
legend.position = c(0.8, 0.87), legend.title = element_blank())

```

```{r, create GPX dataframe}
# let's load up our GPX points
gpx <- htmlTreeParse(file="./data/S-S09-DEP.GPX", useInternalNodes = TRUE)
# coords <- xpathSApply(doc=gpx, path="//trkpt", fun=xmlAttrs)
coords <- xpathSApply(doc = gpx, path = "//wpt", fun = xmlAttrs)
# need to convert to the same CRS

elevation <- xpathSApply(doc = gpx, path = "//wpt", fun = xmlAttrs)
# points <- data.frame(lat=as.numeric(coords["lat", ]),
#                      lon=as.numeric(coords["lon", ]),
#                      elevation=as.numeric(elevation))
gpxXML<-xmlParse(file="S-S09-DEP.GPX", useInternalNodes = TRUE)
gpxPTS <- xmlToDataFrame(gpxXML)
# make cleaner df
gpxPTS<- gpxPTS[-1,] # remove first row
# create df
gpxDF<-data.frame(name=gpxPTS$name,
           time=gpxPTS$time,
           lat=coords[1,],
           lon=coords[2,],
           ele=gpxPTS$ele
           )
gpxDF$lat <- as.numeric(gpxDF$lat)
gpxDF$lon <- as.numeric(gpxDF$lon)
cords <- data.frame(lat=gpxDF$lat, lon=gpxDF$lon)
st_transform(c(gpxDF$lat, gpxDF$lon), "+proj=latlon", "+init=epsg:32615")
cords <- spTransform(cords, crs("+datum=WGS84 +init=epsg:32615"))
coords<- SpatialPoints(cbind(gpxDF$lat,gpxDF$lon), proj4string = CRS("+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs"))
st_transform(coords, CRS=utm)
```

```{r, intersect points and rast}
lonlat<-CRS("+proj=longlat")
lcFencelineSF<-st_as_sf.stars(st_as_stars(lc.fenceline.rast$clipped.area))
proj4string(lc.fenceline.rast$clipped.area) <- CRS("+proj=longlat +datum=WGS84")
lcFarmLonLat <- projectRaster(lc.full, crs="+proj=longlat +datum=WGS84")
lcFarmll <- st_transform(lc.full$clipped.area, lonlat)
plot(lc.fenceline.ll$clipped.area) + 
  points(cbind(gpxDF$lon, gpxDF$lat), pch=19, col="black")
# now can extract landscape values at the points
clipped.hist<-extract(lcFarmLonLat, cbind(gpxDF$lon, gpxDF$lat))
hist(clipped.hist)
```

