```{r}
library(exifr)
library(gtools)
library('rjson')
library(dplyr)
base <-"C:/Users/jackx/Desktop"
site<-"inSample"
cam <- "A112"
basePath<-paste0(base, "/", site)
#basePath<-paste0(base, "/", site, "/", cam)
imgs<-list.files(basePath, pattern=".JPG", full.names=FALSE)
# create a dataframe to hold information about the images
imgDat<-data.frame(name=imgs)
imgDat$improperDateFormate <- FALSE
imgDat$date <- .POSIXct(character(nrow(imgDat)))
if(!dir.exists(paste0(basePath, "/","outOfSample"))){
dir.create(paste0(basePath, "/", "outOfSample"))
}
inSamplePath<-paste0(basePath, "/", "inSample")
outOfSamplePath<-paste0(basePath, "/", "outOfSample")
# create a dataframe of the dates
for(i in 1:nrow(imgDat)){
  exif <-read_exif(paste0(basePath, "/", imgDat[i,]$name))
  if("CreateDate" %in% colnames(exif)){
    imgDat[i,]$date <- as.POSIXct(exif$CreateDate, format="%Y:%m:%d %H:%M")
    # currentDate<-as.POSIXct(exif$CreateDate, format="%Y:%m:%d %H:%M:%OS", tz="")
    }else{
    imgDat[i,]$improperDateFormat <- TRUE
  }
}


```
```{r}
# join imgMetaDat and imgDat
imgDat2 <- data.frame(name="",improperDateFormate=FALSE,date=.POSIXct(character(1)))
#j <- 1
for(i in 1:nrow(imgDat)){
    if(nrow(imgDat[which(imgDat$date == imgDat[i,]$date),]) > 1 & !(imgDat[i,]$date %in% imgDat2$date)){
        imgDat2<-rbind(imgDat2,imgDat[which(imgDat$date == imgDat[i,]$date),][2:nrow(imgDat[which(imgDat$date == imgDat[i,]$date),]),])
        
 # now we can delete so we're not leaving behind a ton of copies
      }
    }
imgDat2<- imgDat2[-1,] # remove first row
for(i in 1:nrow(imgDat2)){
          file.copy(paste0(basePath, "/", imgDat2[i,]$name),
                paste0(outOfSamplePath, "/", imgDat2[i,]$name))
        file.remove(paste0(basePath,"/", imgDat2[i,]$name))
}

```